# Generated by Django 5.0.7 on 2024-07-17 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Crypto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Crypto Name"
                    ),
                ),
                (
                    "symbol",
                    models.CharField(max_length=30, unique=True, verbose_name="Symbol"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Price",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=4, max_digits=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "symbol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        related_query_name="price",
                        to="tracker.crypto",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at",),
            },
        ),
    ]
