# Generated by Django 5.0.7 on 2024-07-19 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_price_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'get_latest_by': 'created_at', 'ordering': ('created_at',)},
        ),
    ]
